
[package]
name = "hourcoin"
version = "0.1.0"
authors = ["Nitesh <niteshkartha@yahoo.com>"]
edition = "2018"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.4.3"
crypto-hash = "0.3.4"